### ISSUE TITLE
Browse project command

### ISSUE THREAD

**Issue by utkarsh867** [deploifai/cli#10]
### Proposed command

```bash
deploifai browse
```

If the project is configured in the directory.

```bash
deploifai browse --project <username/project>
```

For any project from anywhere.

**Comment by 98sean98** [comment]
@utkarsh867 what does browsing mean? does it mean to browse cloud resources? or show project information?

**Comment by utkarsh867** [comment]
Browse means that the link to the project opens in the browser directly.
