### ISSUE TITLE
read local configuration file recursively from current working directory

### ISSUE THREAD

**Issue by 98sean98** [deploifai/cli#18]
When a user is inside the subdirectories of a project, the user should still be able to use the deploifai cli with all its configuration. That means the cli runtime needs to be able to traverse up the directory tree to find the nearest `.deploifai` to get the local configuration file.

**Comment by Richard-B18** [comment]
might be overthinking about this issue, but how to make sure user creates local config file in the root directory of the project? 

`project/.deploifai/local_config.py`

what if user does sth like `deploifai project create` in the `project/deploifai/experiment` or other child directories

**Comment by Richard-B18** [comment]
or is this not possible since local config can only be created when user first initialized a project locally?

**Comment by Richard-B18** [comment]
I think issue is not only reading local config

Assuming my above assumption, and user's local config file is in the right directory which is directly under the initialized project directory, this means that both global and local config file should only be initialized once (unless user deletes it, but we assume this won't happen for now)

this means that whenever a user saves something to the local config file, if user is not in the root project dir, it will create another folder according to how the code works right now
