### ISSUE TITLE
`server create` command

### ISSUE THREAD

**Issue by 98sean98** [deploifai/cli#32]
A user should be able to create a new training server through `server create` command.

**Comment by ExtinctWolf83** [comment]
Argument - Server Name
Then check if they have existing datasets. If no -  ask them to run deploifai data create command. If yes- ask if they want to use the existing dataset, if no - ask them to run deploifai data create command, if yes - prompt them with a list of existing datasets.
Then ask them if they want a virtual machine with GPU or not. If yes - tell them the version of CUDA and CUDIN. If no - don't.
Then ask which ML Framework they plan to use. Then ask which version. Then ask which version of python. Look at all the options, look for the latest version of the framework and then the latest version of python for that framework. Print and show them the information required.
Ask which cloud profile they would like to use. If new ask them to run cloud profile create function.
Then ask them to choose the size of the instance needed. (Small/Medium/Large)
All this information should be enough to deploy a training server.
