### ISSUE TITLE
release cli for package managers to install

### ISSUE THREAD

**Issue by 98sean98** [deploifai/cli#57]
It's kinda annoying to have to install `deploifai` using `pip`. Even amongst ourselves, we don't have the deploifai cli ready in a fresh shell environment.

So it's really beneficial for users to install through `apt` or `brew`.

Target platforms and their preferred package managers:
- ubuntu / debian: apt
- macOS: homebrew
- windows: chocolatey

Look at how `awscli` is released. It's also built using python.

**Comment by 98sean98** [comment]
See https://github.com/deploifai/homebrew-deploifai for our homebrew setup.

**Comment by utkarsh867** [comment]
Updating the tag on the tap formula will do it for homebrew.

**Comment by 98sean98** [comment]
Closed in favor of the [cli-go](https://github.com/deploifai/cli-go) project.
