### ISSUE TITLE
Fetch MLFlow details using the Deploifai API and CLI command

### ISSUE THREAD

**Issue by utkarsh867** [deploifai/cli#6]
These details are there on the dashboard under experiments, but we need to find a way to list it through the CLI, and provide a way to programatically fetch it as well.

<img width="1169" alt="Untitled" src="https://user-images.githubusercontent.com/19630580/174844616-d26286ad-a129-4247-bcfb-33308fa161c0.png">

**Comment by ExtinctWolf83** [comment]
I need a bit of clarification
First, what needs to be done is that this information can be called through the cli?
Second, do we want the code to be added to a project through cli? Or should there be a way to add the code through python?

**Comment by ExtinctWolf83** [comment]
There are two types of experiments, managed runner and external, for MR, needs the last 2 lines only, for external need all 4 lines.
Add an option for external in the command, and provide all 4 lines in that case.
Experiment path: Workspace/Project Name/Experiment Name
Assume that the user is running cli in a folder with a local config
Get the project id from the local config, and get the project name, workspace name, and experiment name from API. If there are multiple experiments give them options to choose the experiment.
For external get token from API.
Tracking URI is constant.
This should provide all the code, show it to the user through cli, and copy it to their clipboard.
