### ISSUE TITLE
adapt configuration file parsers to use tomli

### ISSUE THREAD

**Issue by 98sean98** [deploifai/cli#80]
`config parser` already write configurations in the TOML file format, but config parser is not flexible enough to store deeper objects and lists in the main dictionary. We can use [`tomli`](https://pypi.org/project/tomli/) (which is also adapted as `tomllib` in python 3.11) to load and dump config dictionaries. The API is very similar to `json`.

After loading from a config file, the dictionary can be converted to a custom `Config` class that can contain deeper configuration objects such as `Project`, a list of `Application`s, etc.

**Comment by yawjalik** [comment]
A quick note: existing config files do not use quotes for string values, which will cause issues when reading config files with `tomli`

**Comment by 98sean98** [comment]
Perhaps this project [tomli-w](https://github.com/hukkin/tomli-w) can help with dumping.

**Comment by 98sean98** [comment]
Clean up in favor of the [cli-go](https://github.com/deploifai/cli-go) project
